# -*- coding: utf-8 -*-
"""Azahra Tri Meilani_005_tugas data casting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1idVULhqezk-SA_5rPyzUjSLhp51JfEC6

*   Nama = Azahra Tri Meilani
*   NPM = 2411012005
"""

nama = 'Budi'
usia = 20
lajang = True

print(type(nama))
print(type(usia))
print(type(lajang))

usia = input('Masukkan usia anda: ')

print(type(usia))

a = 10 / 2
print(type(a))

b = 1 / 2
print(type(b))

panjang = int(input('masukkan panjang: '))
lebar = float(input('masukkan lebar: '))

print('luas =', panjang * lebar)

kata = 'jeruk' * 5

print(kata)
print(type(kata))

nama = 'wudi'
tahun_lahir = 2000

print(nama + ' lahir di tahun ' + str(tahun_lahir))