# -*- coding: utf-8 -*-
"""Manipulasi String 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MFhtBBBhLbzQU5qh_58bQUU0bIqgKdY5

Format specifiers
"""

template = 'Halo, saya %s dari %s'

print(template % ('Lendis febri', 'indonesia'))

"""Fungsi format()"""

template = 'halo, saya {nama} dari {asal}'
template_2 = 'saya suka makan {} dan minum {}'

print(template.format(nama = 'lendis febri', asal = 'indonesia'))
print(template_2.format('Nasi Goreng', 'air putih'))

"""string interpolation"""

nama = 'lendis febri'
asal = 'indonesia'

print(f'perkenalkan saya {nama} dari {asal} ')

alamat = 'surabaya, jawa timur, indonesia'

print(alamat.split())
print(alamat.split(','))
print(alamat.split(', '))

print(' '.join(['aku', 'suka', 'phyton']))
print(' '.join(alamat.split(', ')))

print('halo selamat pagi!'.upper())
print('halo selamat siang!'.upper())

print('APA KABAR?'. lower())
print('Lagi Dimana?'.lower())

print('daun tidak pernah membenci angin'.title())
print('LASKAR PELANGI'.title())

print('Indonesia Adalah Negara Kepulauan'.swapcase())
print('aKu cInTa NeGeRiKIu'.swapcase())

"""mencari sebuah kata"""

angka ='12345'

print('Index angka 3:', angka.find('3'))
print('Index angka 45:', angka.find('45'))
print('Index angka 35:', angka.find('35'))

asal = 'lampungu'

print(asal.find('u'))

"""mereplace kata pada string"""

ibu_kota = 'jakarta'

print(ibu_kota.replace('a', 'i'))
print(ibu_kota.replace('kar', ' '))
print(ibu_kota.replace('a', ''))

"""menghitung jumlah karakter yang muncul"""

paragraf = 'Baru-baru ini telah ditemukan sebuah meteor di suatu sungai'
x = paragraf.count('di')
print(f'kata "di" muncul sebanyak {x} kali')