# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eKpz_O1HRziA19M4AmeZCxiDDAyAZZJZ
"""

print('dia berkata: "Pergilah!"')

print("aku menimpali: \"apakah kau ingin aku 'angkat kaki'?!\"")

print (" \\(^_^) / (\\-_-/)")