# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jgFAR998JQ94XIaNzeRmIR_OrxR-RBk_

string
"""

nama = 'azahra tri meilani'
asal = 'indonesia'

print(nama)

print(asal)

print(nama, asal)

print(nama+asal)

print("halo, nama saya")

print("halo, nama saya",nama, "asal saya dari", asal)

data_lengkap = nama + asal

print(data_lengkap)

"""string + non string"""

asal_kota ="way kanan"
kode_pos = 35144

asal_kota_kode_pos = asal_kota + str(kode_pos)

print(asal_kota_kode_pos)

asal_kota = "way kanan"
asal_kota_X3 = asal_kota * 3
print(asal_kota_X3)